### ISSUE TITLE
Convert select tokens field in gui into a list of object

### ISSUE THREAD

**Issue by findolor** [rainlanguage/rain.orderbook#1232]
Currently select tokens field is a list of strings. It will be better if we turn that into:

```
select-tokens:
  - token: input
    name: some name
    description: some description
  - token: output
    name: some name
    description: some description
```
