### ISSUE TITLE
network bindings

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#1261]
# Network Selection and Bindings
## GUI Network Selection
Allows defining a curated list of networks with human-readable names for UI display and selection.
```
gui:
  networks-select:
    <network-key>:
      name: <display-name>
```
Required fields per network:
- name: Human readable display name for the network

The network-key must correspond to a defined network in the networks section.

Example:
```
gui:
  networks-select:
    base:
      name: Base
    flare:
      name: Flare
    arbitrum:
      name: Arbitrum One
```
## Network Bindings

Defines network-specific bindings that can be referenced in scenarios. When a network is selected, its bindings become available in the scenario context.

```
network-bindings:
  <network-key>:
    <binding-name>: <binding-value>
```

- Each network-key must correspond to a defined network in the networks section
- binding-name and binding-value are arbitrary key-value pairs
- Values are treated as strings and passed directly to the scenario context
- Bindings can be referenced in scenarios using ${network-bindings.<binding-name>}
- The active set of bindings is determined by the network of the deployment containing the scenario

Example:

```
network-bindings:
  base:
    raindex-subparser: "0x123abc"
    network-specific-constant: "42"
  
  flare:
    raindex-subparser: "0x456def" 
    flare-specific-value: "some-value"
```

Usage in scenarios:

```
scenarios:
  my-scenario:
    bindings:
      parser-address: ${network-bindings.raindex-subparser}
```

The network-bindings field can appear:
- In the main config YAML
- In separate YAML documents merged into the config
- Directly in .rain files as front matter

When a user selects a network from the networks-select GUI, the corresponding network bindings are automatically made available in the scenario context.

**Comment by hardyjosh** [comment]
On reflection, this isn't the best way to handle network selection for strategies.

The real issue is that we don't want to repeat all of our fields for every gui deployment. So we could solve this by simply allowing for all of the `gui` fields, deposits etc to support multiple deployments. 

For example, right now we have 

```
gui:
  name: Auction based cost averaging
  description: https://raw.githubusercontent.com/rainlanguage/rain.strategies/e25bc4876b5ffb8bb28097b0ca66de291c75ff56/src/auction-dca.md
  short-description:  >
    A strategy that aims to fill a time-based budget via looping auctions - useful for breaking up large trades into smaller amounts or smoothing out market volatility for regular investments.
  deployments:
    arbitrum:
      name: Arbitrum
      description: Deploy an auction-based cost averaging strategy on Arbitrum.
      #....... all of our fields, tokens etc
    bsc:
      name: BSC
      description: Deploy an auction-based cost averaging strategy on BSC.
      #........ all of our fields, tokens etc repeated again
```

this could just be

```
gui:
  name: Auction based cost averaging
  description: https://raw.githubusercontent.com/rainlanguage/rain.strategies/e25bc4876b5ffb8bb28097b0ca66de291c75ff56/src/auction-dca.md
  short-description:  >
    A strategy that aims to fill a time-based budget via looping auctions - useful for breaking up large trades into smaller amounts or smoothing out market volatility for regular investments.
  options:
    default:
      deployments:
       - deployment: arbitrum
          name: Arbitrum
          description: Deploy an auction-based cost averaging strategy on Arbitrum.
       - deployment: flare
          name: Flare
          description: Deploy an auction-based cost averaging strategy on Flare.
      fields: ... # only once
      deposits: .... # only once
      select-tokens: .... # only once
```

Now the variants of how you could configure and deploy the rainlang in the file are called `options` (instead of deployments), and each `option` allows for multiple `deployments`. If the deployments are just one for each network, the user 

1. selects an option (if there's only one, like above, we can skip this step altogether)
2. selects a deployment (network)
3. fills out tokens and fields

The writer of the .rain only has to write out all the fields once. If there is anything network specific in the field names or decriptions, it couild be handled easily with Context, but there's no use case right now.
