### ISSUE TITLE
No data error on deployment debug tab

### ISSUE THREAD

**Issue by findolor** [rainlanguage/rain.orderbook#1656]
## Steps to reproduce

1. Checkout to this [PR](https://github.com/rainlanguage/rain.orderbook/pull/1599) 

2. In the Tauri app use these settings

```yaml
accounts: {}
networks:
  flare:
    rpc: https://flare.rpc.thirdweb.com
    chain-id: 14
    currency: "FLR"
  base:
    rpc: "https://mainnet.base.org"
    chain-id: 8453
    network-id: 8453
    currency: "ETH"
  polygon:
    rpc: "https://rpc.ankr.com/polygon"
    chain-id: 137
    network-id: 137
    currency: "POL"
  arbitrum:
    rpc: "https://rpc.ankr.com/arbitrum"
    chain-id: 42161
    network-id: 42161
    currency: "ETH"
  bsc:
    rpc: "https://rpc.ankr.com/bsc"
    chain-id: 56
    network-id: 56
    currency: "BNB"
  linea:
    rpc: "https://rpc.linea.build"
    chain-id: 59144
    network-id: 59144
    currency: "ETH"
  ethereum:
    rpc: "https://rpc.ankr.com/eth"
    chain-id: 1
    network-id: 1
    currency: "ETH"
subgraphs:
  flare: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-flare/2024-12-13-9dc7/gn
  base: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-base/2024-12-13-9c39/gn"
  polygon: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-matic/2024-12-13-d2b4/gn"
  arbitrum: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-arbitrum-one/2024-12-13-7435/gn"
  bsc: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-bsc/2024-12-13-2244/gn"
  linea: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-linea/2024-12-13-09c7/gn"
  ethereum: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-mainnet/2024-12-13-7f22/gn"
metaboards:
  flare: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-flare-0x893BBFB7/0.1/gn
  base: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-base-0x59401C93/0.1/gn"
  polygon: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-polygon/0.1/gn"
  arbitrum: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-arbitrum/0.1/gn"
  bsc: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-bsc/0.1/gn"
  linea: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-linea-0xed7d6156/1.0.0/gn"
  ethereum: "https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-mainnet/2024-10-25-2857/gn"
orderbooks:
  flare:
    address: 0xCEe8Cd002F151A536394E564b84076c41bBBcD4d
    network: "flare"
    subgraph: "flare"
  base:
    address: "0xd2938e7c9fe3597f78832ce780feb61945c377d7"
    network: "base"
    subgraph: "base"
  polygon:
    address: "0x7D2f700b1f6FD75734824EA4578960747bdF269A"
    network: "polygon"
    subgraph: "polygon"
  arbitrum:
    address: "0x550878091b2B1506069F61ae59e3A5484Bca9166"
    network: "arbitrum"
    subgraph: "arbitrum"
  bsc:
    address: "0xd2938E7c9fe3597F78832CE780Feb61945c377d7"
    network: "bsc"
    subgraph: "bsc"
  linea:
    address: "0x22410e2a46261a1B1e3899a072f303022801C764"
    network: "linea"
    subgraph: "linea"
  ethereum:
    address: "0x0eA6d458488d1cf51695e1D6e4744e6FB715d37C"
    network: "ethereum"
    subgraph: "ethereum"
deployers:
  flare:
    address: 0xE3989Ea7486c0F418C764e6c511e86f6E8830FAb
    network: "flare"
  base:
    address: "0xC1A14cE2fd58A3A2f99deCb8eDd866204eE07f8D"
    network: "base"
  polygon:
    address: "0xE7116BC05C8afe25e5B54b813A74F916B5D42aB1"
    network: "polygon"
  arbitrum:
    address: "0x9B0D254bd858208074De3d2DaF5af11b3D2F377F"
    network: "arbitrum"
  bsc:
    address: "0xA2f56F8F74B7d04d61f281BE6576b6155581dcBA"
    network: "bsc"
  linea:
    address: "0xA2f56F8F74B7d04d61f281BE6576b6155581dcBA"
    network: "linea"
  ethereum:
    address: "0xd19581a021f4704ad4eBfF68258e7A0a9DB1CD77"
    network: "ethereum"
```

3. Use this strat in new order

```yaml
raindex-version: 0
tokens:
    wflr:
        network: flare
        address: 0x1D80c49BbBCd1C0911346656B529DF9E5c2F783d
        decimals: 18
    usdce:
        network: flare
        address: 0xFbDa5F676cB37624f28265A144A48B0d6e87d3b6
        decimals: 6
scenarios:
    flare:
        deployer: flare
        runs: 1
        bindings:
            orderbook-subparser: 0xCEe8Cd002F151A536394E564b84076c41bBBcD4d
orders:
    sell-wflr:
        network: flare
        inputs:
            - token: usdce
              vault-id: 10
        outputs:
            - token: wflr
              vault-id: 20
deployments:
    sell-wflr:
        order: sell-wflr
        scenario: flare
---
#orderbook-subparser !
#calculate-io
using-words-from orderbook-subparser
_: input-token(),
_: input-token-decimals(),
_: input-vault-id(),
_: output-token(),
_: output-token-decimals(),
_: output-vault-id(),
max-output: 30,
io-ratio: mul(0.99 20);
#handle-io
:;
#handle-add-order
:;
```

4. Click on debug tab
