### ISSUE TITLE
specify bindings in the yaml for dotrain

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#181]
take bindings from the yaml like

```
bind:
  - foo: bar
  - baz: 4
  - literal-string: \"stringy thing\"
```

and pass them to dotrain as bindings

note that the above should all be passed to dotrain as _strings_ because we want _rainlang_ to parse the literals, not yaml nor dotrain to parse them

this is the reason for the escaped double quotes above, so that rainlang gets the full string literal in a form that it will know that it is a string
