### ISSUE TITLE
Improved Yaml frontmatter strucure

### ISSUE THREAD

**Issue by mattyg** [rainlanguage/rain.orderbook#286]
```
tokens:
  dai:
    address: 0x...
    decimals: 18
  usdt:
    address: 0x...
    decimals: 6
  usdc:
    address: 0x...
    decimals: 6

orders:
  usdt+dai:
    deployer: 0x...
    valid-inputs:
      - token: dai
        vault-id: 0x...
      - token: usdt
        vault-id: 0x...
    valid-outputs:
      - token: dai
        vault-id: 0x...
      - token: usddt
        vault-id: 0x...
  usdt+usdc+dai:
    deployer: 0x...
    valid-inputs:
      - token: dai
        vault-id: 0x...
      - token: usdt
        vault-id: 0x...
      - token: usdc
        vault-id: 0x...
    valid-outputs:
      - token: dai
        vault-id: 0x...
      - token: usddt
        vault-id: 0x...
      - token: usdcc
        vault-id: 0x...

scenarios:
  main:
    bind:
      - some-binding: 12345
  test:
    runs: 100
    bind:
      - to-be-fuzzed
      - some-binding
```
