### ISSUE TITLE
settings not applied

### ISSUE THREAD

**Issue by mattyg** [rainlanguage/rain.orderbook#397]
upon adding this example settings file and clicking "apply settings", they did not appear in the sidebar which still showed the loading skeleton

- reported on macos 14

```yaml
chains:
  - label: Ethereum public rpc
    rpc-url: https://eth.llamarpc.com
    orderbooks:
      - label: Eth orderbook
        address: 0xf1224A483ad7F1E9aA46A8CE41229F32d7549A74
        subgraph-url: https://api.thegraph.com/subgraphs/name/siddharth2207/xblock
---

#calculate-io
:;

#handle-io
:;
```
