### ISSUE TITLE
Add histogram option for chart time

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#445]
We'll need a way to set bin width - if the charts data is all scaled to 18 decimals, I guess bin width will be also

```
charts:
    mainChart:
        scenario: mumbai
        plots:
            plot1:
                data:. 0.0
                bin-width: 123.45
                plot-type: histogram
```

@thedavidmeister @Siddharth2207 anything you want to add?
