### ISSUE TITLE
Add titles for axes in charts

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#446]
@thedavidmeister @Siddharth2207 thinking this for labelling axes

```
charts:
    mainChart:
        scenario: mumbai
        plots:
            plot1:
                axes:
                    x: my-x-axis
                    y: my-y-axis
                data:
                    x: 0.0
                    y: 0.1
                plot-type: line
```
