### ISSUE TITLE
Set Context in yml options

### ISSUE THREAD

**Issue by Siddharth2207** [rainlanguage/rain.orderbook#447]
Should be able to set orderbook context in `scenarios`. Keys for context could be the same as in orderbook subparser.
Eg:  
```
scenarios:
    polygon-experimental-constant-buy-trend:
        network: polygon
        runs: 1000
        bindings:
            foo:
        context:
            order-hash:
            order-counterparty:
```
