### ISSUE TITLE
support using-networks-from in settings

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#467]
this doesn't have a spec yet but it will be like

```
using-networks-from:
  chainid:
    - url: chainid.network/chains.json
    - format: chainid
    ```
