### ISSUE TITLE
ability to quote bind data transformations while charting

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#472]
somethign like this

```
data:
  x:
    stack-position: 0.3
    transform: '''effective-price'
  y: 0.1
  ```
  
  need to update spec

basically this would avoid the need to modify the main body expressions for calculate/handle io to wrangle data for better charting
