### ISSUE TITLE
undefined deployer address

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#522]
<img width="577" alt="Screenshot 2024-04-03 at 08 58 04" src="https://github.com/rainlanguage/rain.orderbook/assets/629710/6ea13373-4ae4-4ff8-ac1a-c069ec8bb54f">

getting this error, even though i can deploy

order

```
tokens:
  usdt:
    address: 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9
    decimals: 6
    network: arbitrum-one
  weth:
    address: 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1
    decimals: 18
    network: arbitrum-one

orders:
  arbitrum-one:
    inputs:
      - token: weth
        vault-id: 0x0fc7631ed56aaec24ba6f621fbd37a332ac7e9b25d42dcfb0e30fc59240fb900
    outputs:
      - token: usdt
        vault-id: 0x0fc7631ed56aaec24ba6f621fbd37a332ac7e9b25d42dcfb0e30fc59240fb900

scenarios:
  arbitrum-one:
    network: arbitrum-one
    deployer: arbitrum-one

deployments:
  arbitrum-one:
    scenario: arbitrum-one
    order: arbitrum-one

---
#calculate-io
_ _:0 0;

#handle-io
:;
```

settings

```
networks: 
  polygon: 
    rpc: https://rpc.ankr.com/polygon 
    chain-id: 137 
    network-id: 137 
    currency: MATIC
  mainnet: 
    rpc: https://1rpc.io/eth 
    chain-id: 1 
    network-id: 1 
    currency: ETH
  arbitrum-one: 
    rpc: https://1rpc.io/arb 
    chain-id: 42161 
    network-id: 42161 
    currency: ETH
  flare:
    rpc: https://rpc.ankr.com/flare	
    chain-id: 14
    network-id: 14
    currency: FLR
  
subgraphs:
  polygon: https://api.thegraph.com/subgraphs/name/h20liquidity/polygon-0xc95a5f8e
  mainnet: https://api.thegraph.com/subgraphs/name/h20liquidity/ethereum-0xf1224a48
  arbitrum-one: https://api.thegraph.com/subgraphs/name/h20liquidity/arbitrum-0x90caf23e
  flare: https://subgraphs.h20liquidity.tech/subgraphs/name/flare-ob

orderbooks:
  polygon:
    address: 0xc95A5f8eFe14d7a20BD2E5BAFEC4E71f8Ce0B9A6
    network: polygon
    subgraph: polygon
  mainnet:
    address: 0xf1224A483ad7F1E9aA46A8CE41229F32d7549A74
    network: mainnet
    subgraph: mainnet
  arbitrum-one:
    address: 0x90CAF23eA7E507BB722647B0674e50D8d6468234
    network: arbitrum-one
    subgraph: arbitrum-one
  flare:
    address: 0xF9bDedb1e8c32185E879E056eBA9F5aeC1839d60
    network: flare
    subgraph: flare

deployers:
  polygon:
    address: 0xF77b3c3f61af5a3cE7f7CE3cfFc117491104432E
    network: polygon
  mainnet:
    address: 0x4D69ec4d0112E42c385B5cCb6897cCdfeAfC3136
    network: mainnet
  arbitrum-one:
    address: 0x2AeE87D75CD000583DAEC7A28db103B1c0c18b76
    network: arbitrum-one
  flare:
    address: 0xd19581a021f4704ad4eBfF68258e7A0a9DB1CD77
    network: flare

```
