### ISSUE TITLE
Orderbook for the network needs to be mentioned explicitly in `orders` section in yml

### ISSUE THREAD

**Issue by Siddharth2207** [rainlanguage/rain.orderbook#591]
Eg : 
```
orders:
  bsc-order:
    orderbook: bsc
    inputs:
      - token: bsc-usdt
        vault-id: 0x3679c0a98e0467c1d764d58dff377906930e6bf0e875b1bce96d8abd973b157c
    outputs:
      - token: bsc-usdc
        vault-id: 0x3679c0a98e0467c1d764d58dff377906930e6bf0e875b1bce96d8abd973b157c
```
Need to mention `orderbook` key and the network.
