### ISSUE TITLE
App freezing on order page

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#875]
When i got the app and go to order hash 0x46c95656cfa84321134b2476afc81d2011e6759c4b80317b8911bbebbe2f39df

The app appears to freeze. Using the settings below:

```
networks:
  matchain:
    rpc: https://dataseed-mainnet-private-rpc-1.matchain.io
    chain-id: 698
    currency: BNB
  
subgraphs:
  matchain: http://subgraph.mobula.io:8000/subgraphs/name/matchain-ob
  
orderbooks:
  matchain:
    address: 0x40312EDAB8Fe65091354172ad79e9459f21094E2
    network: matchain
    subgraph: matchain

deployers:
  matchain:
    address: 0x582d9e838FE6cD9F8147C66A8f56A3FBE513a6A2
```
