### ISSUE TITLE
`Words` tab errors for nested scenarios within the front matter.

### ISSUE THREAD

**Issue by Siddharth2207** [rainlanguage/rain.orderbook#969]
- If scenarios hierarchy that nested scenarios then the `Words` tab errors.
```yaml
scenarios:
  foo:
    bindings:
      key: <value>
```
`Words` tab is resolved. 
```yaml
scenarios:
  foo:
    bindings:
      key: <value>
    scenarios:
        bar:
          bindings:
            key: <value>
```
Words tab errors. 
![image](https://github.com/user-attachments/assets/0ed63c5a-9346-4791-b5c8-ca44b65f3500)
